[env:crowpanel_7]
platform = espressif32 @ 5.3.0
board = crowpanel7
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; ESP32-S3-WROOM-1-N4R8: 4MB Flash, 8MB OPI PSRAM
board_build.partitions = min_spiffs.csv
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -I ${PROJECT_INCLUDE_DIR}

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    lvgl/lvgl @ ^8.3.11
    bblanchon/ArduinoJson @ ^7.0.0
    arduino-libraries/NTPClient @ ^3.2.1
    tzapu/WiFiManager @ ^2.0.17
    Wire
