[env:crowpanel_7]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 4MB

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_INCLUDE_SIMPLE

lib_deps =
    moononournation/GFX Library for Arduino @ ^1.4.9
    lvgl/lvgl @ ^8.3.11
    bblanchon/ArduinoJson @ ^7.0.0
    arduino-libraries/NTPClient @ ^3.2.1
    tzapu/WiFiManager @ ^2.0.17
    ricmoo/QRCode @ ^0.0.1
    Wire
